name: Deploy Frontend
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub using GitHub's Docker login action
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build the Docker image
      - name: Build Docker Image
        run: docker build -t cygnetops/react-test -f Dockerfile.dev .

      # Step 4: Run tests inside the Docker container
      - name: Run Tests
        run: docker run -e CI=true cygnetops/react-test npm test